#!/bin/bash

case "$1" in
  start)
	conky -c /home/lmy/Config/conky.conf &
  ;;

  restart|reload|force-reload)
    $0 stop
    $0 start
  ;;

  stop)
	killall conky
	killall -9 conky
  ;;

  status)
	if [ "`ps aux | grep conky | grep -v grep`" ]; then
		echo "conky is active!"
	else
		echo "conky is not active."
	fi
  ;;
  
  *)
    echo "Usage: $0 {start|stop|status|restart|reload|force-reload}"
    exit 1
    ;;
esac

exit 0
