#!/bin/bash

case "$1" in
  start)
    wbar -isize 48 -config ~/Config/wbar.conf -jumpf 0.2 -pos top -nofont &
  ;;

  restart|reload|force-reload)
    $0 stop
    $0 start
  ;;

  stop)
	killall wbar
	killall -9 wbar
  ;;

  status)
	if [ "`ps aux | grep wbar | grep -v grep`" ]; then
		echo "wbar is active!"
	else
		echo "wbar is not active."
	fi
  ;;
  
  *)
    echo "Usage: $0 {start|stop|status|restart|reload|force-reload}"
    exit 1
    ;;
esac

exit 0
