#!/bin/sh

# keymap
xmodmap "/home/lmy/.Xmodmap"

# Applications
/home/lmy/Config/conky start
nm-applet &
nitrogen --restore &
xcompmgr &

# autostart apps
#pcmanfm /media/stuff/music &
#audacious &
lxterminal &
#firefox &
fbsetbg -l
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/lmy/.fluxbox/log"
